# Generated by Django 2.2.6 on 2020-05-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200522_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_house_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pb_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.PublishingHouse'),
        ),
    ]
