# Generated by Django 2.2.6 on 2020-05-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_friend_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
